name: Check and Update Arch Packages

on:
  schedule:
    - cron: "0 0 * * 1" # Weekly on Monday
  workflow_dispatch:

jobs:
  check-and-update-arch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Arch Linux in Docker
        run: |
          # Pull Arch Linux Docker image
          docker pull archlinux:latest

          # Mount the repository into the Docker container
          docker run --rm -v $PWD:/workspace archlinux:latest /bin/bash -c "
            set -e
            # Step 1: Update pacman and install dependencies
            pacman -Syu --noconfirm

            # Step 2: Check package updates
            while IFS= read -r package; do
              # Check if the package is installed
              if pacman -Qi $package > /dev/null 2>&1; then
                # Extract repository information
                repo=\$(pacman -Qi $package | grep 'Repository' | awk '{print \$3}')

                # Skip if the package belongs to a third-party repository
                if [ \"\$repo\" != \"core\" ] && [ \"\$repo\" != \"extra\" ] && [ \"\$repo\" != \"community\" ]; then
                  echo \"$package is from a third-party repository (\$repo). Skipping.\" >> /workspace/Linux_Setup/Packages/pkglist_arch_x86_updates.txt
                  continue
                fi

                # Check for updates
                if pacman -Qu $package > /dev/null 2>&1; then
                  echo \"$package has updates available.\" >> /workspace/Linux_Setup/Packages/pkglist_arch_x86_updates.txt
                else
                  echo \"$package is up to date.\" >> /workspace/Linux_Setup/Packages/pkglist_arch_x86_updates.txt
                fi
              else
                echo \"$package is not installed.\" >> /workspace/Linux_Setup/Packages/pkglist_arch_x86_updates.txt
              fi
            done < /workspace/Linux_Setup/Packages/pkglist_arch_x86.txt
          "

      - name: Commit and Push Changes (if any)
        run: |
          if [ -s Linux_Setup/Packages/pkglist_arch_x86_updates.txt ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add Linux_Setup/Packages/pkglist_arch_x86_updates.txt
            git commit -m "chore: update Arch Linux package list with available updates"
            git push
          else
            echo "No updates found."
