name: Update Pacman Packages

on:
  schedule:
    - cron: "0 0 * * 1" # Weekly on Monday
  workflow_dispatch:

jobs:
  update-arch:
    runs-on: ubuntu-latest
    steps:
      - name: Run Arch Linux in Docker
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull Arch Linux Docker Image
        run: docker pull archlinux:latest

      - name: Update Pacman Packages
        run: |
          docker run --rm archlinux:latest /bin/bash -c "pacman -Syu --noconfirm"
